apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sjm-py-tastpa-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjm-py-tastpa-1 
  name: sjm-py-tastpa-1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sjm-py-tastpa-1 
